2014-04-14 19:36:13 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:36:57 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:36:57 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:39:54 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:43:02 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:43:45 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:43:46 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:43:59 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:43:59 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:00 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:00 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:53 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:54 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:54 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:55 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:55 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:55 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:44:55 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:45:11 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:45:11 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:50:10 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:50:39 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 19:51:16 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 19:56:48 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:58:42 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:58:48 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 19:59:05 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 20:00:56 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 20:02:25 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:10:18 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:10:19 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:10:30 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:10:31 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:10:32 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:10:38 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\pedidoonline\app\Controller\PostsController.php(7): Model->find('all')
#7 [internal function]: PostsController->index()
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 20:10:44 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-14 20:21:06 Error: [MissingDatasourceConfigException] The datasource configuration "default" was not found in database.php
Exception Attributes: array (
  'config' => 'default',
)
Request URL: /pedidoonline/posts/add
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\ConnectionManager.php(91): ConnectionManager::_getConnectionObject('default')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('posts')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\View\Helper\FormHelper.php(207): Model->schema()
#6 D:\xampp\htdocs\pedidoonline\lib\Cake\View\Helper\FormHelper.php(459): FormHelper->_introspectModel('Post', 'fields')
#7 D:\xampp\htdocs\pedidoonline\app\View\posts\add.ctp(3): FormHelper->create('Post')
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(935): include('D:\xampp\htdocs...')
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(897): View->_evaluate('D:\xampp\htdocs...', Array)
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(466): View->_render('D:\xampp\htdocs...')
#11 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#12 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#13 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#14 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2014-04-14 23:17:23 Error: [MissingControllerException] Controller class ClienteController could not be found.
Exception Attributes: array (
  'class' => 'ClienteController',
  'plugin' => NULL,
)
Request URL: /pedidoonline/cliente
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-14 23:17:33 Error: [MissingTableException] Table clientes for model Cliente was not found in datasource default.
Exception Attributes: array (
  'table' => 'clientes',
  'class' => 'Cliente',
  'ds' => 'default',
)
Request URL: /pedidoonline/clientes/add
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(3499): Model->setSource('clientes')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\View\Helper\FormHelper.php(207): Model->schema()
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\View\Helper\FormHelper.php(459): FormHelper->_introspectModel('Cliente', 'fields')
#4 D:\xampp\htdocs\pedidoonline\app\View\Clientes\add.ctp(3): FormHelper->create('Cliente')
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(935): include('D:\xampp\htdocs...')
#6 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(897): View->_evaluate('D:\xampp\htdocs...', Array)
#7 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(466): View->_render('D:\xampp\htdocs...')
#8 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#9 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#10 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-04-14 23:39:55 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\pedidoonline\app\Controller\ClientesController.php, line 7]
2014-04-14 23:39:55 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 7, Array)
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 7, Array)
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-15 01:31:53 Error: [MissingControllerException] Controller class ViewController could not be found.
Exception Attributes: array (
  'class' => 'ViewController',
  'plugin' => NULL,
)
Request URL: /pedidoonline/view/2
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-15 02:17:40 Error: Fatal Error (64): Cannot redeclare ClientesController::index() in [D:\xampp\htdocs\pedidoonline\app\Controller\ClientesController.php, line 9]
2014-04-15 02:17:40 Error: [FatalErrorException] Cannot redeclare ClientesController::index()
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'D:\xampp\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'D:\xampp\htdocs...', 9, Array)
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'D:\xampp\htdocs...', 9, Array)
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-15 02:19:13 Error: [MissingControllerException] Controller class ViewController could not be found.
Exception Attributes: array (
  'class' => 'ViewController',
  'plugin' => NULL,
)
Request URL: /pedidoonline/view/2
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-15 02:19:17 Error: [MissingActionException] Action PostsController::display() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'display',
)
Request URL: /pedidoonline/
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-15 02:20:24 Error: [MissingActionException] Action ClientesController::display() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'display',
)
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-15 02:20:25 Error: [MissingActionException] Action ClientesController::display() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'display',
)
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-15 02:20:27 Error: [MissingActionException] Action ClientesController::display() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'display',
)
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-15 02:20:28 Error: [MissingActionException] Action ClientesController::display() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'display',
)
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-15 02:23:44 Error: [MissingViewException] View file "D:\xampp\htdocs\pedidoonline\app\View\Clientes\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\pedidoonline\\app\\View\\Clientes\\index.ctp',
)
Request URL: /pedidoonline/clientes
Stack Trace:
#0 D:\xampp\htdocs\pedidoonline\lib\Cake\View\View.php(463): View->_getViewFileName('index')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(954): View->render('index', NULL)
#2 D:\xampp\htdocs\pedidoonline\app\Controller\ClientesController.php(31): Controller->render('index')
#3 [internal function]: ClientesController->display('index')
#4 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ClientesController), Array)
#5 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#6 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#7 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-04-16 14:38:45 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /pedidoonline/clientes/delete/3
Stack Trace:
#0 [internal function]: ClientesController->delete('3')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ClientesController), Array)
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-16 15:59:31 Error: [MethodNotAllowedException] Method Not Allowed
Request URL: /pedidoonline/clientes/delete/11
Stack Trace:
#0 [internal function]: ClientesController->delete('11')
#1 D:\xampp\htdocs\pedidoonline\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ClientesController), Array)
#2 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 D:\xampp\htdocs\pedidoonline\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedidoonline\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-21 22:22:21 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /pedido/app/
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-21 22:22:26 Error: [MissingActionException] Action AppController::cidades() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'cidades',
)
Request URL: /pedido/app/cidades
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-22 22:42:33 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-22 22:45:34 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-22 22:45:39 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-22 22:45:39 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-22 22:45:59 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-22 22:46:13 Error: [MissingViewException] View file "D:\xampp\htdocs\pedido\app\View\Cidades\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\pedido\\app\\View\\Cidades\\index.ctp',
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\pedido\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-22 22:47:22 Error: [MissingViewException] View file "D:\xampp\htdocs\pedido\app\View\Cidades\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\pedido\\app\\View\\Cidades\\index.ctp',
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\pedido\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-22 22:47:25 Error: [MissingViewException] View file "D:\xampp\htdocs\pedido\app\View\Cidades\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\pedido\\app\\View\\Cidades\\index.ctp',
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\pedido\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-22 22:49:26 Error: [MissingViewException] View file "D:\xampp\htdocs\pedido\app\View\Cidades\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\pedido\\app\\View\\Cidades\\index.ctp',
)
Request URL: /pedido/
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\pedido\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-22 22:59:15 Error: [MissingViewException] View file "D:\xampp\htdocs\pedido\app\View\Cidades\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\pedido\\app\\View\\Cidades\\index.ctp',
)
Request URL: /pedido/cidades
Stack Trace:
#0 D:\xampp\htdocs\pedido\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\pedido\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 D:\xampp\htdocs\pedido\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\pedido\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-23 11:54:19 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1049] Unknown database \'pedidoonline\'',
  'enabled' => true,
)
Request URL: /pedidos/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Model\ConnectionManager.php(105): DboSource->__construct(Array)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Model.php(3477): ConnectionManager::getDataSource('default')
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Model.php(1126): Model->setDataSource('default')
#4 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Model.php(3499): Model->setSource('cidades')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Model.php(2903): Model->getDataSource()
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#8 C:\SENAI\Fontes\pedidos\app\Controller\CidadesController.php(25): PaginatorComponent->paginate()
#9 [internal function]: CidadesController->index()
#10 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(CidadesController), Array)
#11 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#13 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-04-23 12:14:29 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [C:\SENAI\Fontes\pedidos\app\View\Cidades\add.ctp, line 31]
2014-04-23 12:14:29 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Request URL: /pedidos/cidades/add
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\SENAI\Fontes...', 31)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\SENAI\Fontes...', 31, Array)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\SENAI\Fontes...', 31, Array)
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-23 13:24:58 Error: [MissingViewException] View file "C:\SENAI\Fontes\pedidos\app\View\Cidades\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\SENAI\\Fontes\\pedidos\\app\\View\\Cidades\\index.ctp',
)
Request URL: /pedidos/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(463): View->_getViewFileName(NULL)
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CidadesController), Object(CakeRequest), Object(CakeResponse))
#4 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-23 13:31:15 Error: [MissingControllerException] Controller class EstadosController could not be found.
Exception Attributes: array (
  'class' => 'EstadosController',
  'plugin' => NULL,
)
Request URL: /pedidos/estados
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-23 13:55:13 Error: Fatal Error (1): Class 'Config' not found in [C:\SENAI\Fontes\pedidos\app\Config\bootstrap.php, line 91]
2014-04-23 13:55:13 Error: [FatalErrorException] Class 'Config' not found
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'Config' ...', 'C:\SENAI\Fontes...', 91)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Config' ...', 'C:\SENAI\Fontes...', 91, Array)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Class 'Config' ...', 'C:\SENAI\Fontes...', 91, Array)
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-23 14:08:13 Error: [MissingHelperException] Helper class LocaleHelper could not be found.
Exception Attributes: array (
  'class' => 'LocaleHelper',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Locale')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(824): HelperCollection->__isset('Locale')
#2 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): View->__get('Locale')
#3 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#4 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#8 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#9 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-04-23 14:11:01 Error: [MissingHelperException] Helper class LocaleHelper could not be found.
Exception Attributes: array (
  'class' => 'LocaleHelper',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Locale')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(824): HelperCollection->__isset('Locale')
#2 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): View->__get('Locale')
#3 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#4 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#8 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#9 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-04-23 14:12:27 Error: [MissingHelperException] Helper class LocaleHelper could not be found.
Exception Attributes: array (
  'class' => 'LocaleHelper',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Locale')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(824): HelperCollection->__isset('Locale')
#2 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): View->__get('Locale')
#3 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#4 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#8 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#9 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-04-23 14:15:51 Error: [MissingPluginException] Plugin Locale could not be found.
Exception Attributes: array (
  'plugin' => 'Locale',
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Locale')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Locale')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Lib', 'Locale')
#3 [internal function]: App::load('Formats')
#4 C:\SENAI\Fontes\pedidos\app\View\Helper\LocaleHelper.php(68): spl_autoload_call('Formats')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(136): LocaleHelper->__construct(Object(View), Array)
#6 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Locale')
#7 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(824): HelperCollection->__isset('Locale')
#8 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): View->__get('Locale')
#9 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#10 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#11 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#12 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#13 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#14 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#15 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-04-23 14:16:14 Error: Fatal Error (1): Class 'Config' not found in [C:\SENAI\Fontes\pedidos\app\Config\bootstrap.php, line 96]
2014-04-23 14:16:14 Error: [FatalErrorException] Class 'Config' not found
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'Config' ...', 'C:\SENAI\Fontes...', 96)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Config' ...', 'C:\SENAI\Fontes...', 96, Array)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Class 'Config' ...', 'C:\SENAI\Fontes...', 96, Array)
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-23 11:21:30 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 11:21:53 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 11:21:54 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 11:21:55 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 11:21:56 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 11:21:56 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 11:21:56 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 14:22:11 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\app\Config\bootstrap.php(97): CakePlugin::load('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\Configure.php(92): include('C:\SENAI\Fontes...')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\bootstrap.php(175): Configure::bootstrap(true)
#3 C:\SENAI\Fontes\pedidos\app\webroot\index.php(90): include('C:\SENAI\Fontes...')
#4 {main}
2014-04-23 11:22:19 Error: [MissingPluginException] Plugin Language could not be found.
Exception Attributes: array (
  'plugin' => 'Language',
)
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Language')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Language')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Routing/Filter', 'Language')
#3 [internal function]: App::load('default')
#4 [internal function]: spl_autoload_call('default')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(105): class_exists('default')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(70): Dispatcher->_attachFilters(Object(CakeEventManager))
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(140): Dispatcher->getEventManager()
#8 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-04-23 14:27:18 Error: [MissingPluginException] Plugin Locale could not be found.
Exception Attributes: array (
  'plugin' => 'Locale',
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(365): CakePlugin::path('Locale')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(226): App::pluginPath('Locale')
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(547): App::path('Lib', 'Locale')
#3 [internal function]: App::load('Formats')
#4 C:\SENAI\Fontes\pedidos\app\View\Helper\LocaleHelper.php(68): spl_autoload_call('Formats')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(136): LocaleHelper->__construct(Object(View), Array)
#6 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Locale')
#7 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(824): HelperCollection->__isset('Locale')
#8 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): View->__get('Locale')
#9 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#10 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#11 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#12 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#13 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#14 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#15 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-04-23 14:55:00 Error: [MissingBehaviorException] Behavior class DataPtBrBehavior could not be found.
Exception Attributes: array (
  'class' => 'DataPtBrBehavior',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Model\BehaviorCollection.php(66): BehaviorCollection->load('DataPtBr', Array)
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Model\Model.php(747): BehaviorCollection->init('Estado', Array)
#2 [internal function]: Model->__construct(Array)
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Utility\ClassRegistry.php(168): ReflectionClass->newInstance(Array)
#4 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(738): ClassRegistry::init(Array)
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(367): Controller->loadModel('Estado')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(405): Controller->__isset('Estado')
#7 C:\SENAI\Fontes\pedidos\app\Controller\EstadosController.php(36): Controller->__get('Estado')
#8 [internal function]: EstadosController->view('2')
#9 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(EstadosController), Array)
#10 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#12 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-04-23 16:48:32 Error: [MissingHelperException] Helper class DataPtBrHelper could not be found.
Exception Attributes: array (
  'class' => 'DataPtBrHelper',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(873): HelperCollection->load('DataPtBr', Array)
#1 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(347): View->loadHelpers()
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(1241): View->__construct(Object(EstadosController))
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(940): Controller->_getViewObject()
#4 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#6 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-04-23 16:48:48 Error: [MissingHelperException] Helper class DataPtBrHelper could not be found.
Exception Attributes: array (
  'class' => 'DataPtBrHelper',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(873): HelperCollection->load('DataPtBr', Array)
#1 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(347): View->loadHelpers()
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(1241): View->__construct(Object(EstadosController))
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(940): Controller->_getViewObject()
#4 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#5 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#6 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-04-23 16:50:46 Error: [MissingHelperException] Helper class dateHelper could not be found.
Exception Attributes: array (
  'class' => 'dateHelper',
  'plugin' => false,
)
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('date')
#1 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(824): HelperCollection->__isset('date')
#2 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): View->__get('date')
#3 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#4 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#6 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#8 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#9 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-04-23 17:10:32 Error: [Exception] DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.
Request URL: /pedidos/estados/view/2
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\app\Plugin\locale\Lib\Utils.php(68): DateTime->__construct()
#1 C:\SENAI\Fontes\pedidos\app\Plugin\locale\Lib\Localize.php(89): Utils::initDateTime('2014-04-23 13:3...')
#2 C:\SENAI\Fontes\pedidos\app\Plugin\locale\View\Helper\LocaleHelper.php(84): Localize::date('2014-04-23 13:3...')
#3 C:\SENAI\Fontes\pedidos\app\View\Estados\view.ctp(50): LocaleHelper->date('2014-04-23 13:3...')
#4 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(935): include('C:\SENAI\Fontes...')
#5 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(897): View->_evaluate('C:\SENAI\Fontes...', Array)
#6 C:\SENAI\Fontes\pedidos\lib\Cake\View\View.php(466): View->_render('C:\SENAI\Fontes...')
#7 C:\SENAI\Fontes\pedidos\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#8 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#9 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(EstadosController), Object(CakeRequest), Object(CakeResponse))
#10 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2014-04-23 14:31:04 Error: [MissingControllerException] Controller class EmpresasController could not be found.
Exception Attributes: array (
  'class' => 'EmpresasController',
  'plugin' => NULL,
)
Request URL: /pedidos/empresas
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-23 14:31:22 Error: [MissingControllerException] Controller class PedidosItensController could not be found.
Exception Attributes: array (
  'class' => 'PedidosItensController',
  'plugin' => NULL,
)
Request URL: /pedidos/pedidos_itens/add
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-23 14:31:29 Error: [MissingControllerException] Controller class PedidosController could not be found.
Exception Attributes: array (
  'class' => 'PedidosController',
  'plugin' => NULL,
)
Request URL: /pedidos/pedidos
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-04-23 16:48:42 Error: [MissingActionException] Action ClientesController::cidades() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'cidades',
)
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-23 16:48:58 Error: [MissingActionException] Action ClientesController::cidades() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'cidades',
)
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-23 16:49:33 Error: [MissingActionException] Action ClientesController::cidades() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'cidades',
)
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-23 16:49:33 Error: Fatal Error (4): syntax error, unexpected '/' in [C:\SENAI\Fontes\pedidos\app\View\Elements\navigation.ctp, line 16]
2014-04-23 16:49:33 Error: [FatalErrorException] syntax error, unexpected '/'
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\SENAI\Fontes...', 16)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\SENAI\Fontes...', 16, Array)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\SENAI\Fontes...', 16, Array)
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-23 16:49:46 Error: [MissingActionException] Action ClientesController::cidades() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'cidades',
)
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-23 16:49:46 Error: Fatal Error (1): Call to undefined method View::url() in [C:\SENAI\Fontes\pedidos\app\View\Elements\navigation.ctp, line 14]
2014-04-23 16:49:46 Error: [FatalErrorException] Call to undefined method View::url()
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\SENAI\Fontes...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\SENAI\Fontes...', 14, Array)
#2 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\SENAI\Fontes...', 14, Array)
#3 C:\SENAI\Fontes\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-23 16:50:23 Error: [MissingActionException] Action ClientesController::cidades() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'cidades',
)
Request URL: /pedidos/clientes/cidades
Stack Trace:
#0 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\SENAI\Fontes\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest), Object(CakeResponse))
#2 C:\SENAI\Fontes\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-04-23 20:23:27 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\pedidos\app\Controller\ProdutosController.php, line 59]
2014-04-23 20:23:27 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /pedidos/produtos/add
Stack Trace:
#0 C:\xampp\htdocs\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 59, Array)
#2 C:\xampp\htdocs\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 59, Array)
#3 C:\xampp\htdocs\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-04-23 20:26:58 Error: [NotFoundException] Invalid produto
Request URL: /pedidos/produtos/view
Stack Trace:
#0 [internal function]: ProdutosController->view()
#1 C:\xampp\htdocs\pedidos\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ProdutosController), Array)
#2 C:\xampp\htdocs\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ProdutosController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-23 20:27:25 Error: [NotFoundException] Invalid produto
Request URL: /pedidos/produtos/view/1
Stack Trace:
#0 [internal function]: ProdutosController->view('1')
#1 C:\xampp\htdocs\pedidos\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ProdutosController), Array)
#2 C:\xampp\htdocs\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ProdutosController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-23 20:27:35 Error: [NotFoundException] Invalid produto
Request URL: /pedidos/produtos/view/2
Stack Trace:
#0 [internal function]: ProdutosController->view('2')
#1 C:\xampp\htdocs\pedidos\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ProdutosController), Array)
#2 C:\xampp\htdocs\pedidos\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\pedidos\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(ProdutosController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\pedidos\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-04-23 20:40:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\pedidos\app\Controller\ProdutosController.php, line 86]
2014-04-23 20:40:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /pedidos/produtos/edit/1
Stack Trace:
#0 C:\xampp\htdocs\pedidos\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86, Array)
#2 C:\xampp\htdocs\pedidos\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 86, Array)
#3 C:\xampp\htdocs\pedidos\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
